### PR TITLE
Add Mathematics Extension

### PR DESCRIPTION
**Pull request by imalfect**
This pull request implements the TipTap Pro mathematics extension (`@tiptap-pro/extension-mathematics`) into the editor.

### CODE REVIEW

**Comment by imalfect** [comment]
I was afraid that my katex css import might break the editor in case katex is not installed, but I just checked and it works just fine.

**Comment by gbicou** [comment]
thanks will look

**Comment by gbicou** [comment]
cherry picked and released in v1.16.0

**Comment by imalfect** [comment]
Thank you, appreciate it. Btw, is more tiptap extensions something that this directus extension would benefit from? I will be adding a couple to my blog instance, so perhaps I could also open pull requests for those so that the community can benefit from it.

**Comment by gbicou** [comment]
yes sure, I added only the pro extensions I use but feel free to open pull requests.

**Pull request closed without merging**
